name: Build APK

on:
  push:
    branches:
      - prernarawar77
  pull_request:
    branches:
      - prernarawat77

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'adoptopenjdk'

      - name: Install dependencies
        run: ./gradlew dependencies

      - name: Build APK
        run: ./gradlew assembleRelease
        env:
          JAVA_HOME: /usr/lib/jvm/adoptopenjdk-11

      - name: Archive APK
        uses: actions/upload-artifact@v3
        with:
          name: apk
          path: app/build/outputs/apk/release/app-release.apk
